name: Enforce 2 collaborator reviews for fork PRs

on:
  pull_request_review:
    types: [submitted]

permissions:
  pull-requests: read

jobs:
  enforce-reviews:
    runs-on: self-hosted
    steps:
      - name: Check if PR is from a fork
        id: fork_check
        run: |
          echo "is_fork=${{ github.event.pull_request.head.repo.full_name != github.repository }}" >> $GITHUB_ENV

      - name: Fetch approved reviews by collaborators
        if: env.is_fork == 'true'
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO="${{ github.repository }}"

          REVIEWS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/$REPO/pulls/$PR_NUMBER/reviews")

          COUNT=$(echo "$REVIEWS" | jq '[.[] | select(.state=="APPROVED" and .author_association=="COLLABORATOR") | .user.login] | unique | length')

          echo "Collaborator approvals: $COUNT"
          if [ "$COUNT" -lt 2 ]; then
            echo "❌ PR from fork requires 2 collaborator approvals."
            exit 1
          fi
