name: Enforce 2 collaborator reviews for fork PRs

on:
  pull_request_review:
    types: [submitted]

permissions:
  pull-requests: read

jobs:
  enforce-reviews:
    runs-on: self-hosted
    steps:
      - name: Check 2 trusted collaborators rule
        run: |
          if "${{ github.event.pull_request.head.repo.full_name == github.repository }}"; then
            echo "✅ PR is not from fork, 1 collaborator approval is enough"
            exit 0
          fi
          
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO="${{ github.repository }}"

          REVIEWS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/$REPO/pulls/$PR_NUMBER/reviews")

          COUNT=$(echo "$REVIEWS" | jq '[.[] | select(.state=="APPROVED" and .author_association=="COLLABORATOR") | .user.login] | unique | length')

          echo "Collaborator approvals: $COUNT"
          if [ "$COUNT" -lt 2 ]; then
            echo "❌ PR from fork requires 2 collaborator approvals."
            exit 1
          fi
